#Programming language
language: cpp

# Compilers
compiler:
    - gcc

# Linux dist
dist: trusty

# Dependencies
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - build-essential
      - libboost-all-dev
      - zlib1g
      - zlib1g-dev
      - doxygen
      - cmake
      - libcppunit*

# Create build env
before_script:
    - mkdir build
    - cmake -H. -Bbuild
        -DBUILD_TESTS=1

# Build steps
script:
    #- cmake --build build -- -j all doc
    - cmake --build build -- -j

after_success:
    - cd build
    - ctest -V #run tests
