version: '{build}'

# Build worker image (VM template)
os: Visual Studio 2015

# specify custom environment variables
environment:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_62_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_62_0\lib32-msvc-14.0
    ZLIB_ROOT: C:\projects\zlib
    ZLIB_INCLUDE: C:\projects\zlib\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\include
    ZLIB_LIBRARY: C:\projects\zlib\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\Win32\Release\zlib.lib
    DOXYGEN_ROOT: C:\projects\doxygen
    DOXYGEN_EXE: C:\projects\doxygen\Doxygen.1.8.9.2\tools\doxygen.exe
    CPPUNIT_ROOT: C:\projects\cppunit
    CPPUNIT_INCLUDE_DIR: C:\projects\cppunit\cppunit-1.13.2\include
    CPPUNIT_LIBRARY: C:\projects\cppunit\cppunit-1.13.2\lib\cppunit.lib

init:
    - cmd: cmake --version
    - cmd: msbuild /version

install:
    - nuget install zlib -outputdirectory "%ZLIB_ROOT%"
    #- tree /A /F "%ZLIB_ROOT%" #for debug

    #- nuget install cppunit -outputdirectory "%CPPUNIT_ROOT%" #there is no VS2015 version
    - md %CPPUNIT_ROOT%
    - curl -o %CPPUNIT_ROOT%\cppunit.tar.gz http://dev-www.libreoffice.org/src/cppunit-1.13.2.tar.gz
    - 7z x %CPPUNIT_ROOT%\cppunit.tar.gz -so | 7z x -si -ttar -o%CPPUNIT_ROOT%
    - tree /A /F "%CPPUNIT_ROOT%" #for debug
    - msbuild %CPPUNIT_ROOT%\cppunit-1.13.2\src\CppUnitLibraries2010.sln /p:Configuration=Release /target:cppunit
    - tree /A /F "%CPPUNIT_ROOT%" #for debug

    - nuget install Doxygen -outputdirectory "%DOXYGEN_ROOT%"

before_build:
    - md build
    - cmake -H. -Bbuild
        -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"
        -DDOXYGEN_EXECUTABLE="%DOXYGEN_EXE%"
        -DZLIB_INCLUDE_DIR="%ZLIB_INCLUDE%" -DZLIB_LIBRARY="%ZLIB_LIBRARY%"
        -DCPPUNIT_INCLUDE_DIR="%CPPUNIT_INCLUDE_DIR%"
        -DCPPUNIT_LIBRARY_RELEASE="%CPPUNIT_LIBRARY%"
        #-DCPPUNIT_ROOT_DIR="%CPPUNIT_ROOT%\cppunit-1.13.2"
        -DBUILD_TESTS=1

build_script:
    - cmake --build build --config Release
    - cmake --build build --config Release --target doc

test_script:
    - cd build
    - ctest -V
