version: '{build}'

# Build worker image (VM template)
#image:
#    - Visual Studio 2015
#    - Visual Studio 2017

# specify custom environment variables
environment:
    MSVC_DEFAULT_OPTIONS: ON
    VCPKG_BIN: C:\tools\vcpkg\installed\x86-windows\bin

    ZLIB_INCLUDE: C:\tools\vcpkg\installed\x86-windows\include
    ZLIB_LIBRARY: C:\tools\vcpkg\installed\x86-windows\lib\zlib.lib

    DOXYGEN_ROOT: C:\projects\doxygen
    DOXYGEN_EXE: C:\projects\doxygen\Doxygen.1.8.13\tools\doxygen.exe

    CPPUNIT_INCLUDE_DIR: C:\tools\vcpkg\installed\x86-windows\include
    CPPUNIT_LIBRARY: C:\tools\vcpkg\installed\x86-windows\lib\cppunit_dll.lib

    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          BOOST_ROOT: C:\Libraries\boost_1_63_0
          BOOST_LIBRARYDIR: C:\Libraries\boost_1_63_0\lib32-msvc-14.0
          #BOOST_INCLUDE_DIR: C:\tools\vcpkg\installed\x86-windows\include
          #BOOST_LIBRARYDIR: C:\tools\vcpkg\installed\x86-windows\lib

        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          BOOST_ROOT: C:\Libraries\boost_1_65_1
          BOOST_LIBRARYDIR: C:\Libraries\boost_1_65_1\lib32-msvc-14.1
          #BOOST_INCLUDE_DIR: C:\tools\vcpkg\installed\x86-windows\include
          #BOOST_LIBRARYDIR: C:\tools\vcpkg\installed\x86-windows\lib

init:
    - cmd: cmake --version
    - cmd: msbuild /version
    - cmd: vcpkg cache

cache:
    - C:\tools\vcpkg\installed\

install:
    - vcpkg install zlib
    - vcpkg install cppunit
    - vcpkg install boost #This is also possible, but way to slow. Instead we use the preinstalled boost.
    - nuget install Doxygen -outputdirectory "%DOXYGEN_ROOT%"

before_build:
    - md build
    - cmake -H. -Bbuild
        -DBOOST_ROOT=%BOOST_ROOT% -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"
        -DDOXYGEN_EXECUTABLE="%DOXYGEN_EXE%"
        -DZLIB_INCLUDE_DIR="%ZLIB_INCLUDE%" -DZLIB_LIBRARY="%ZLIB_LIBRARY%"
        -DCPPUNIT_INCLUDE_DIR="%CPPUNIT_INCLUDE_DIR%" -DCPPUNIT_LIBRARY_RELEASE="%CPPUNIT_LIBRARY%"
        -DBUILD_TESTS=1

build_script:
    #build sources
    - cmake --build build --config Release --

    #build doc
    #- cmake --build build --config Release --target doc

test_script:
    #- cmd: set PATH=%PATH%;%BOOST_LIBRARYDIR%
    - cmd: set PATH=%PATH%;%VCPKG_BIN%

    - cmd: cd build
    #- tree /A /F .
    - cmd: ctest -V -C Release
