version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

install:
    - nuget install zlib

before_build:
    - md build
    - cmake -H. -Bbuild -DBOOST_ROOT=C:\Libraries\boost -DZLIB_INCLUDE_DIRS="C:\projects\cppzip" -DZLIB_LIBRARIES="C:\projects\cppzip"

build_script:
- cmake --build build --
