version: '{build}'

# Build worker image (VM template)
os: Visual Studio 2015

# specify custom environment variables
environment:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_62_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_62_0\lib32-msvc-14.0
    ZLIB_ROOT: C:\projects\zlib
    ZLIB_INCLUDE: C:\projects\zlib\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\build\native\include
    ZLIB_LIBRARY: C:\projects\zlib\zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8\lib\native\v140\windesktop\msvcstl\dyn\rt-dyn\Win32\Release\zlib.lib
    DOXYGEN_EXE: C:\projects\doxygen\Doxygen.1.8.9.2\tools\doxygen.exe

init:
    - cmd: cmake --version
    - cmd: msbuild /version

install:
    - nuget install zlib -outputdirectory "%ZLIB_ROOT%"
    #- tree /A /F "%ZLIB_ROOT%" #for debug
    - nuget install cppunit -outputdirectory "C:\projects\cppunit"
    - nuget install Doxygen -outputdirectory "%DOXYGEN_DIR%"

before_build:
    - md build
    - cmake -H. -Bbuild
        -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"
        -DDOXYGEN_EXECUTABLE="%DOXYGEN_EXE%"
        -DZLIB_INCLUDE_DIR="%ZLIB_INCLUDE%" -DZLIB_LIBRARY="%ZLIB_LIBRARY%"

build_script:
    - cmake --build build --config Release
    - cmake --build build --config Release --target doc
