version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

install:
    - nuget install zlib cppunit

before_build:
    - md build
    - cmake -H. -Bbuild \
        -DBOOST_ROOT=C:\Libraries\boost \
        -DZLIB_INCLUDE_DIR="C:\projects\cppzip" -DZLIB_LIBRARY="C:\projects\cppzip"

build_script:
- cmake --build build --
