version: '{build}'

# Build worker image (VM template)
os: Visual Studio 2015

# specify custom environment variables
environment:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_62_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_62_0\lib32-msvc-14.0
    ZLIB_DIR: C:\projects\zlib\zlib.1.2.8.8\zlib.1.2.8.8
    DOXYGEN_DIR: C:\projects\doxygen

init:
    - cmd: cmake --version
    - cmd: msbuild /version

install:
    - nuget install zlib -outputdirectory "%ZLIB_DIR%"
    - dir "%ZLIB_DIR%"
    - nuget install cppunit -outputdirectory "C:\projects\cppunit"
    - nuget install Doxygen -outputdirectory "%DOXYGEN_DIR%"

before_build:
    - md build
    - cmake --help-policy CMP0045
    - cmake -H. -Bbuild
        -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"
        -DZLIB_INCLUDE_DIR="%ZLIB_DIR%" -DZLIB_LIBRARY="%ZLIB_DIR%"
        -DDOXYGEN_EXECUTABLE="%DOXYGEN_DIR%"

build_script:
- cmake --build build --
