version: '{build}'

# Build worker image (VM template)
image: Visual Studio 2015

before_build:
    - md build
    - cmake -H. -Bbuild -DBOOST_ROOT=C:\Libraries\boost

build_script:
- cmake --build build --
