version: '{build}'

# Build worker image (VM template)
os: Visual Studio 2015

init:
    - cmd: cmake --version
    - cmd: msbuild /version

install:
    - nuget install zlib -outputdirectory "C:\projects\zlib"
    - nuget install cppunit -outputdirectory "C:\projects\cppunit"
    - nuget install Doxygen -outputdirectory "C:\projects\doxygen"
    #- nuget install boost -outputdirectory "C:\projects\boost"
    #- dir "C:\projects\boost\boost.1.62.0.0"

before_build:
    - md build
    - dir C:\Libraries\boost_1_62_0
    - cmake -H. -Bbuild
        -DBOOST_ROOT="C:\Libraries\boost_1_62_0" -DBOOST_LIBRARYDIR="C:\Libraries\boost_1_62_0\lib32-msvc-14.0"
        -DZLIB_INCLUDE_DIR="C:\projects\zlib" -DZLIB_LIBRARY="C:\projects\zlib"
        -DDOXYGEN_EXECUTABLE="C:\projects\doxygen"

build_script:
- cmake --build build --
